### ISSUE TITLE
Could GitHub Actions Cache throttling lead to nix crashes ?

### ISSUE THREAD

**Issue by layus** [DeterminateSystems/magic-nix-cache#101]
I encountered a crash on nix CI. As I did not change any code related to nix, I think the issue may come from the only warning/error messages in the log, and these relate to magic-nix-cache and GitHub Actions Cache throttling. In the end, nix daemon crashes

Obviously nix should never crash, but there is possibly some improvements that can be made to magic-nix-cache to handle throttling more transparently.

See https://github.com/NixOS/nix/issues/11511 for the details.

**Comment by Mic92** [comment]
@layus could you check https://github.com/NixOS/nix/pull/11600

**Comment by layus** [comment]
Seems like this is a nix failure, closing this issue
