### ISSUE TITLE
Guix support

### ISSUE THREAD

**Issue by viperML** [DeterminateSystems/magic-nix-cache#59]
Would be it be very complicated to also support guix? On a naive approach, just `s#/nix/store#/gnu/store/`, but I don't know how coupled is the project with nix.

**Comment by lucperkins** [comment]
@viperML Guix is certainly inspired by Nix in a multitude of ways and I suspect that their respective caching stories have some deep structural similarities. But the Magic Nix Cache is completely tied to Nix&mdash;the daemon, the Nix store, the NAR concept&mdash;and we have no intention to expand it to support Guix.

**Comment by viperML** [comment]
So are you interacting with the store directly via its protocol?

**Comment by lucperkins** [comment]
The MNC mimics a Nix binary cache from Nix's standpoint and writes to either the GitHub Actions cache via its API or to FlakeHub Cache (depending on the user's preferences).

**Comment by viperML** [comment]
Just to note, I get that you are not intersted by this, but I will try implement this on my own for a fork. So I just wanted to poll on potential idiosyncrasies of GHA or nix itself 🙂

**Comment by lucperkins** [comment]
No worries! Happy to answer questions to the best of our ability. It's an intriguing idea, just not one that we really have the bandwidth to pursue 😀
